backend:
  name: github
  repo: damemuchamarcha-bot/web1
  branch: main
  base_url: https://decap-cms-oauth-orcin.vercel.app
  auth_endpoint: auth

publish_mode: editorial_workflow

media_library:
  name: uploadcare
  config:
    publicKey: "0c8ace87549de321b182"
    tabs: "file url camera gdrive"
    effects: "crop,rotate"
    settings:
      crop: "21:9, 16:9, 4:3, 1:1, free"

media_folder: "public/uploads"
public_folder: "/uploads"

slug:
  clean_accents: true

collections:
  - name: "articles"
    label: "Artículos"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Resumen (Excerpt)", name: "excerpt", widget: "text"}
      - {label: "Autor", name: "author", widget: "string", default: "Dame Marcha"}
      - {label: "Sección", name: "section", widget: "select", options: ["musica", "cine"]}
      - {label: "Categoría", name: "categoryLabel", widget: "string"}
      - {label: "Imagen de Portada", name: "image", widget: "image"}
      
      # Campo de galería opcional para TODAS las entradas
      - label: "Galería de fotos (Mosaico)"
        name: "galeria"
        widget: "list"
        required: false
        hint: "Sube las fotos que quieras añadir a la galería del artículo"
        field:
          label: "Imagen"
          name: "image"
          widget: "image"

      - {label: "Contenido del Artículo", name: "body", widget: "markdown"}
